INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_0');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_1');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_2');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_3');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_4');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_5');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_6');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_7');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_8');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_9');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_10');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_11');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_12');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_13');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_14');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_15');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_16');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_17');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_18');
INSERT INTO "airplane_type" (airplane_type) VALUES ('airplane_type_19');

INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_0',1,12);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_1',6,16);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_2',2,14);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_3',17,2);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_4',19,18);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_5',16,16);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_6',3,13);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_7',7,18);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_8',9,6);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_9',6,10);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_10',2,6);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_11',14,7);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_12',19,13);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_13',20,8);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_14',2,19);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_15',8,15);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_16',4,11);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_17',12,17);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_18',16,12);
INSERT INTO "airplanes" (name,airplane_type_id,capacity) VALUES ('airplanes_19',20,1);

INSERT INTO "bookups" (trip_id,passenger_id) VALUES (2,4);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (4,9);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (2,14);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (4,18);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (18,5);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (3,19);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (12,14);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (10,18);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (10,5);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (4,18);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (9,9);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (7,2);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (20,6);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (2,14);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (10,3);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (14,16);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (5,2);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (8,8);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (18,9);
INSERT INTO "bookups" (trip_id,passenger_id) VALUES (8,13);

INSERT INTO "destinations" (country) VALUES ('destinations_0');
INSERT INTO "destinations" (country) VALUES ('destinations_1');
INSERT INTO "destinations" (country) VALUES ('destinations_2');
INSERT INTO "destinations" (country) VALUES ('destinations_3');
INSERT INTO "destinations" (country) VALUES ('destinations_4');
INSERT INTO "destinations" (country) VALUES ('destinations_5');
INSERT INTO "destinations" (country) VALUES ('destinations_6');
INSERT INTO "destinations" (country) VALUES ('destinations_7');
INSERT INTO "destinations" (country) VALUES ('destinations_8');
INSERT INTO "destinations" (country) VALUES ('destinations_9');
INSERT INTO "destinations" (country) VALUES ('destinations_10');
INSERT INTO "destinations" (country) VALUES ('destinations_11');
INSERT INTO "destinations" (country) VALUES ('destinations_12');
INSERT INTO "destinations" (country) VALUES ('destinations_13');
INSERT INTO "destinations" (country) VALUES ('destinations_14');
INSERT INTO "destinations" (country) VALUES ('destinations_15');
INSERT INTO "destinations" (country) VALUES ('destinations_16');
INSERT INTO "destinations" (country) VALUES ('destinations_17');
INSERT INTO "destinations" (country) VALUES ('destinations_18');
INSERT INTO "destinations" (country) VALUES ('destinations_19');

INSERT INTO "passenger_information" (phone,name) VALUES ('+375525688537','passenger_information_0');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375086970642','passenger_information_1');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375935481263','passenger_information_2');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375877236511','passenger_information_3');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375564157924','passenger_information_4');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375854778947','passenger_information_5');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375106082163','passenger_information_6');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375568697708','passenger_information_7');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375549421330','passenger_information_8');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375042044064','passenger_information_9');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375374991399','passenger_information_10');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375337543558','passenger_information_11');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375014003818','passenger_information_12');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375684206251','passenger_information_13');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375262204319','passenger_information_14');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375864598523','passenger_information_15');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375881378482','passenger_information_16');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375500554172','passenger_information_17');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375819076666','passenger_information_18');
INSERT INTO "passenger_information" (phone,name) VALUES ('+375871722919','passenger_information_19');

INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (8,CONVERT(DATETIME, '2020-4-10 14:56:6'),7,9);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (4,CONVERT(DATETIME, '2020-10-23 1:35:27'),11,13);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (3,CONVERT(DATETIME, '2020-4-23 12:52:9'),3,16);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (7,CONVERT(DATETIME, '2020-2-25 3:26:39'),7,1);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (2,CONVERT(DATETIME, '2020-9-25 23:25:54'),7,17);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (1,CONVERT(DATETIME, '2020-11-20 11:39:55'),3,1);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (11,CONVERT(DATETIME, '2020-12-6 10:3:38'),15,9);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (4,CONVERT(DATETIME, '2020-9-17 12:38:1'),11,14);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (11,CONVERT(DATETIME, '2020-1-17 20:7:31'),6,18);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (4,CONVERT(DATETIME, '2020-3-9 1:8:4'),14,19);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (6,CONVERT(DATETIME, '2020-6-4 16:28:25'),11,12);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (8,CONVERT(DATETIME, '2020-2-23 3:14:13'),3,3);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (3,CONVERT(DATETIME, '2020-1-2 7:32:43'),16,17);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (2,CONVERT(DATETIME, '2020-4-2 23:21:27'),15,6);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (2,CONVERT(DATETIME, '2020-7-15 2:17:8'),12,20);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (19,CONVERT(DATETIME, '2020-8-16 6:11:8'),8,6);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (13,CONVERT(DATETIME, '2020-3-15 6:19:44'),12,6);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (5,CONVERT(DATETIME, '2020-11-2 10:56:53'),20,1);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (3,CONVERT(DATETIME, '2020-1-16 19:44:5'),6,16);
INSERT INTO "trips" (airplane_id,date,destination_id,arrival_id) VALUES (20,CONVERT(DATETIME, '2020-12-7 8:30:11'),1,4);